num_classes: 11
batch_size: 2
num_workers: 8
learning_rate: 0.0001
weight_decay: 0.0005
subset_size: 100
num_epochs: 1
train_val_split: [0.8, 0.2]
img_dim: 128
freeze_backbone: True
model_type: faster_rcnn_resnet50_fpn
