IMG_PATH: assignment_data_bdd/bdd100k_images_100k/bdd100k/images/100k
LABELS_PATH: assignment_data_bdd/bdd100k_labels_release/bdd100k/labels
TRAIN_LABELS_JSON: assignment_data_bdd/bdd100k_labels_release/bdd100k/labels/bdd100k_labels_images_train.json
VAL_LABELS_JSON: assignment_data_bdd/bdd100k_labels_release/bdd100k/labels/bdd100k_labels_images_val.json

num_classes: 10
batch_size: 14
num_workers: 8
learning_rate: 0.01
num_epochs: 1
img_dim: 64
model_type: yolov8n
custom_model: False
project_name: bdd_yolov8